### ISSUE TITLE
New term for (measurement) replicate

### ISSUE THREAD

**Issue by jonrkarr** [MaastrichtU-IDS/semanticscience#88]
Name: replicate

Description: One of multiple measurements of a system

Subclass of: SIO_000257, SIO_001258

**Comment by micheldumontier** [comment]
being a replicate is a role that an object plays in relation to another set of objects - typically where they are exact copies.  can you elaborate the context in which you want to apply this term?

**Comment by jonrkarr** [comment]
We want to describe that an experiment (object) is a replicate (member) of a set of equivalent experiments.

In the context of experimental science, investigators often conduct multiple independent replicate experiments for the purpose of helping determine that results are real rather than artifacts of mistakes (which are unlikely to be repeated). Each replicate is designed to be equivalent. The replicates differ in that they are independently executed by different people, at different times, potentially with different equipment.

We aim to use SIO to annotate the semantic meaning of the results of computational simulation experiments. In the context of stochastic simulations, investigators frequently execute multiple simulations to sample the modeled distribution (also often called an "ensemble"). These simulations are replicates in a similar sense as used in experimental science. The simulations only differ in the seed used for the random number generator involved in the execution of the simulation.

**Comment by micheldumontier** [comment]
ok. replicate has id of SIO_001418

you should be careful here. because of the positioning of this role-based class, there's the possibility of an inconsistent ontology if you directly instantiate this class with objects of a type that is disjoint with this one. you should really type the object as specifically as you can, and annotate it with a role that is in relation to other objects, or as a member of the replicate collection.

**Comment by micheldumontier** [comment]
SIO:001417 is 'replicate role'
