### ISSUE TITLE
classify salt under chemical complex

### ISSUE THREAD

**Issue by cmungall** [MaastrichtU-IDS/semanticscience#96]
chemical complex: A chemical complex is a chemical substance composed of a weakly connected molecules and ions in a known stoichiometry.

chemical salt: a chemical salt is a heterogenous substance composed of an ionic assembly of cations and anions.

currently salt is *not* a subclass of complex. Should it be?

E.g. take hexahydrate Co(NO3)2·6H2O - this is both a salt and a chemical complex, as the stoichiometry is known?

**Comment by micheldumontier** [comment]
At the moment, a chemical salt is necessarily a heterogeneous substance, because we expect that there are two different species (molecules) involved in the interaction.  a chemical complex could very well be composed of two instances of the same molecule type, and therefore homogeneous. note that chemical complex and heterogeneous substance are *not* disjoint.

**Comment by micheldumontier** [comment]
in OWL-DL, we can't express that there are 2 or more of the same or different type...

**Comment by micheldumontier** [comment]
in the case of cobalt nitrate hexahydrate - we'd expect that there would be compositionally 3 constituents - water, nitric acid, and cobalt, and this would form a set of salts including anhydrous cobalt-dinitrate salt, and a variety of cobalt-dinitrate hydrates (OH- groups coordinating around the cobalt).

**Comment by micheldumontier** [comment]
Moving chemical salt to molecular complex and adjust definition. created new class 'salt' as a heterogeneous substance for compounds.
